# Generated by Django 3.2.8 on 2021-10-12 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=18, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('no_hp', models.CharField(max_length=15, unique=True)),
                ('jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='staf_pegawai.jabatan')),
            ],
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_akun', models.CharField(choices=[('pegawai', 'Pegawai'), ('admin', 'Administrator')], max_length=20)),
                ('akun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staf_pegawai.pegawai')),
            ],
        ),
    ]
