# Generated by Django 3.2.8 on 2021-12-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staf_pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan', models.CharField(choices=[('PNS', 'Pegawai Negeri Sipil'), ('Cleaning Service', 'Cleaning Service'), ('Staf Administratip bagian rumah sakit', 'staf'), ('CPNS', 'CPNS'), ('Staf RSUD', 'Staf RSUD'), ('Penjaga Malam', 'Penjaga Malam'), ('Persandian', 'Persandian'), ('Operator Telepon', 'Operator Telepon'), ('Regu Pagi', 'Regu Pagi'), ('Regu Siang', 'Regu Siang'), ('Regu Malam', 'Regu Malam')], max_length=150)),
                ('pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staf_pegawai.pegawai')),
            ],
        ),
    ]
