# Generated by Django 3.2.8 on 2021-12-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staf_pegawai', '0002_golongan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.CharField(choices=[('Sangat Puas', 'Sangat Puas'), ('Puas', 'Puas'), ('Cukup', 'Cukup'), ('Tidak Puas', 'Tidak Puas'), ('Sangat Buruk', 'Sangat Buruk')], max_length=200)),
                ('masukkan', models.TextField(max_length=1000)),
                ('pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staf_pegawai.pegawai')),
            ],
        ),
    ]
