# Generated by Django 3.2.8 on 2021-10-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staf_pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('A', 'Tanpa Keterangan'), ('I', 'Ijin'), ('S', 'Sakit')], default='H', max_length=1)),
                ('waktu_masuk', models.DateTimeField()),
                ('waktu_keluar', models.DateTimeField(blank=True)),
                ('pegawai', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='staf_pegawai.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('keterangan', models.CharField(max_length=200)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='staf_pegawai.pegawai')),
            ],
        ),
    ]
