# Generated by Django 3.2.8 on 2021-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi_manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='last_update_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status',
            field=models.CharField(choices=[('hadir', 'hadir'), ('alpa', 'alpa'), ('ijin', 'ijin'), ('sakit', 'sakit')], max_length=200),
        ),
    ]
